Addition of saveMeta node
cmccarthy1/automl-1 pull request #25
Opened 2020-10-27 12:48 UTC by Dianeod

- Reviewed by Deanna

2020-10-27 12:50 UTC, Dianeod commented
- Addition of saveMeta node

- Removed`pathDict` parameter from `pathConstruct` as it's already created in `dataCheck`

2020-10-27 13:06 UTC, cmccarthy1 commented on code/nodes/pathConstruct/pathConstruct.q
>    paths:pathConstruct.constructPath[preProcParams];
no need to assign this now

2020-10-27 17:13 UTC, Dianeod commented
- All comments resolved

- Addition of tests in saveMeta to ensure correct data is being saved down

- Addition of tests in pathConstruct to ensure correct directories are being created

2020-10-28 12:13 UTC, cmccarthy1 requested changes

2020-10-28 12:13 UTC, cmccarthy1 commented on code/nodes/saveMeta/tests/test.t
> +system"rm -r ",rmPath;
Windows deletion also needs to be supported

2020-10-28 12:20 UTC, merged